### ISSUE TITLE
Why HAProxy 

### ISSUE THREAD

**Issue by abitrolly** [kinaklub/next.filmfest.by#98]
From https://github.com/kinaklub/next.filmfest.by/pull/83#issuecomment-271268886:

> @abitrolly I have plans to get rid of nginx and replace it with haproxy
> let's close this pr

@nott I remember we were discussing the issue, but don't remember the outcome. Two problems with these plans:

1. Neither me, not @davojta have hands-on experience with HAProxy (@davojta, correct me if I wrong), but I tuned Nginx more than once

So to protect project from you being hit by a bus (something that happens to me weekly), we'll have to learn HAProxy. Now there is already a big [stack of technologies](https://github.com/kinaklub/next.filmfest.by/pull/99/files) we've built upon, and until we find time to learn new kata, this just adds to our **debt of competence** (where only only one person possesses know-how).

2. There is no arguments technical explanation why HAProxy is better alternative for us to already working Nginx

I understand that all of us constantly need new toys to play, and that is keep us motivated, creative, and keeps open source fun. But I find it less fun when [Google chooses NGINX](https://cloud.google.com/endpoints/docs/quickstart-compute-engine#running_the_extensible_service_proxy) and we abandon it without any sound argument about a better alternative.

So I hope you agree to list your arguments once again here, or give a public talk about it on Linux meetup, and we can invoke a power of [VideoBro](https://github.com/kinaklub/videobro) to make a sound reference. =)

**Comment by staaas** [comment]
@abitrolly 

So I've been working on deploy and pipeline recently. My current goal is to enable automatic updates in production.

### Some arguments

* we don't use Nginx anywhere today (there is [production.yml](https://github.com/kinaklub/next.filmfest.by/blob/75db87e72f242771efcdbbe362001cc98048421c/production.yml), but it isn't used anymore)
* I tried to fit Nginx into my deployment scheme, but I couldn't
  * what I needed was upstream reconfiguration in runtime, but that's available only in Nginx+ (which is paid)
  * well, to be perfectly honest, I could live with Nginx, but that makes deployment pipeline more complicated without a real reason
* HAProxy and Nginx both work for our needs:
  * both can work as HTTP proxy
  * both protect worker pool from slow clients
  * both can do SSL termination

### Why do I need upstream reconfiguration

So (Nginx|HAProxy) will act as an HTTP proxy. I want them to resolve app container via DNS name (instead of using IP addresses). However Nginx won't even start in this case - it performs DNS lookups at startup.

> @nott, can we just use IP addresses?

Probably, yes (I haven't tried though)

> @nott, if Nginx crashes at startup, can it just crash-loop until address can be resolved?

Probably, yes (well, changing IP address of app container will require manual restart of Nginx, but that still can be acceptable)

### Instead of a conclusion

I don't have much experience with HAProxy too. But I can see this as a compromise for a simple (and I hope reliable) deployment scheme. You'll be able to review my PR anyway.

**Comment by staaas** [comment]
we've switched to haproxy - we now use this [haproxy.cfg](https://github.com/kinaklub/docker-filmfest-haproxy/blob/9944b58a21872120166cf22c9b7e734a828b812f/haproxy.cfg)

looks like haproxy is a better option for http proxy in dockerized environment these days because it can do dns resolving in run time
